config/routes.rb
DeborahcGcosmin0LourdProj3::Application.routes.draw do
  resources :users
  resources :sessions
  resources :events
  resources :payments
  resources :purchases

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "landing_page" => "welcome#landing", :as => "landing_page"

  get 'events/:id/close_event' => 'events#close_event', :as => 'close_event'

  root :to => "events#index"

    get '/404' =>'errors#not_found'

  

end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :organizer, :class_name => "User", :foreign_key 	=> 'organizer'
	has_many :user_event_balances, dependent: :destroy
	has_many :payments, dependent: :destroy
	has_many :purchases, dependent: :destroy
	has_many :users, through: :user_event_balances

	# The total balance of an event is the total amount of purchases for that event
	def update_total_balance
		self.update_attribute(:total_balance, self.purchases.sum('amount'))
		self.total_balance
	end

	# Set an event as closed so it can stop accepting purchases or payments anymore
	def close_event
    	self.update_attribute(:closed, true)
  end

	# Wrapper method to find the user_event_balance attached to a specific event and id
	def find_user_event_balance(user_id)
		self.user_event_balances.find_by_user_id(user_id)
	end

  # Method to determine the total amount paid by a user to the event
	def find_total_payments_made_by_user(user_id)
		sum = 0
		if !self.payments.find_all_by_user_id(user_id).nil?
			self.payments.find_all_by_user_id(user_id).each do |payment|
				sum += payment.amount
			end
		end
		sum
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :close_event]

  before_action :check_organizer_permissions, only: [:destroy, :edit, :update, :close_event]
  before_action :check_show_permissions, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new

    @all_users = User.where(['id <> ?', current_user.id])

    @user_event_balance = @event.user_event_balances.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(:name => event_params[:name],
      :description => event_params[:description],
      :total_balance => 0, :organizer => current_user, :closed => false)

    unless params[:users][:id].include? current_user.id.to_s()
      params[:users][:id] << current_user.id.to_s()
    end

    params[:users][:id].each do |user|
      unless user.empty?
        @event.user_event_balances.build(:credit => 0, :debt => 0, :payment_received =>0, :user_id => user)
      end
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  # GET /events/1/close_event
  def close_event
    @event.close_event

    redirect_to(:back)
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description)
  end

  def check_organizer_permissions
    if @event.organizer.id != current_user.id
      redirect_to root_url, :notice => "You can't access this page"
    end
  end

  def check_show_permissions
    unless @event.organizer.id == current_user.id or get_users_in_event(@event).include? current_user.id
      redirect_to root_url, :notice => "You can't access this page"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, :placeholder => "Event name" %>
    <%= f.text_area :description, :placeholder => "Description of the event"%>
  <% if @event.new_record? %>
    <%= fields_for(@user_event_balance) do |usb| %>
        <%= usb.label "Choose users participating in the event (choose multiple with ctrl+click)" %> <br />
        <%= collection_select(:users, :id, User.find(:all, :conditions => ["id != ?", current_user.id]), :id, :email, {}, {:multiple => true, :size => 10, class:"chzn-select medium"}) %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit :class => "my-btn gr-btn"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="back-buttons">
	<%= button_to @event, :class => 'my-btn gr-btn back-btn', :method => :get do %>
		Back to event
	<% end %>

	<%= button_to events_path, :class => 'my-btn gr-btn back-btn', :method => :get do %>
		All events
	<% end %>
</div>

<div class="new-event-container">
	<h1>Editing event</h1>
	<%= render 'form' %>
</div>

app/views/events/index.html.erb
<div id="events-left">

<table class="table event-table">
  <thead>
    <tr>
      <th>Event Name</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td class="event-name"><%= link_to event.name, event_path(event) %></td>       
        <td class="event-row-actions">
          <% if event.closed == false %>
          
            <%= link_to new_payment_url + "?event_id=" + event.id.to_s(), :method => :get, :title => "Add payment" do %>
            <i class="fa fa-money fa-2x"></i>
            <% end %>

            <%= link_to new_purchase_url + "?event_id=" + event.id.to_s(), :method => :get, :title => "Add purchase" do %>
            <i class="fa fa-shopping-cart fa-2x"></i>
            <% end %>
            
          <% end %>
        
          <% if event.organizer.id == current_user.id %>
            <% if event.closed == false %>
              <%= link_to close_event_path(event), :method => :get, :title => "Close event", data: {confirm: "Are you sure? This will make users unable to add any more purchases or payments to the event!"} do %>
              <i class="fa fa-check-circle fa-2x"></i>
              <% end %>

              <%= link_to edit_event_path(event), :method => :get, :title => "Edit event" do %>
              <i class="fa fa-edit fa-2x"></i>
              <% end %>
            <% end %>
              
            <%= link_to event, :method => :delete, :title => "Delete event", data: {confirm: 'Are you sure you want to delete this event?'} do %>
            <i class="fa fa-trash-o fa-2x"></i>
            <% end %>

          <% end %>
        </td>

        <td class="event-row-text pull-right">
          <% if event.find_user_event_balance(current_user.id).debt > 0 %>
            You owe <text class="debt-text"><%=number_to_currency(event.find_user_event_balance(current_user.id).debt)%></text>
            <% elsif event.find_user_event_balance(current_user.id).credit > 0 %>
            You're owed <text class="credit-text"><%=number_to_currency(event.find_user_event_balance(current_user.id).credit)%></text>
            <% else %>
            Settled up!
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div id="events-right">
  <h2 class="my-h2" id="owe-text">You owe: <text id="total-debt"><%= number_to_currency(current_user.total_debt) %></text></h2>
  <h2 class="my-h2" id="owed-text">You're owed: <text id="total-credit"><%= number_to_currency(current_user.total_credit) %></text></h2>
  <%= button_to('New Event', new_event_path, :class => 'my-btn gr-btn', :method => :get) %>
  <%= button_to('Purchase History', purchases_path, :class => 'my-btn gr-btn', :method => :get) %>
  <%= button_to('Payment History', payments_path, :class => 'my-btn gr-btn', :method => :get) %>
</div>  

app/views/events/new.html.erb
<div class="back-buttons">
	<%= button_to events_path, :class => 'my-btn gr-btn back-btn', :method => :get do %>
		Back
	<% end %>	
</div>

<div class="new-event-container">
	<h1>New event</h1>
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<div id="events-show-left">
	<%= button_to events_path, :class => 'my-btn gr-btn', :method => :get do %>
	Back to all events
	<% end %>
	<h3 class="organizer-text">Organizer</h3>
	<p><%= "#{@event.organizer.first_name} #{@event.organizer.last_name}" %></p>
	<table class="table member-table">
		<thead>
			<tr>
				<th>Members</th>
			</tr>
		</thead>
		<tbody>
			<% @event.users.each do |user| %>
				<tr>
					<td class="member-name"><%="#{user.first_name} #{user.last_name}"%></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div id="events-show-middle">
	<h2 id="event-title">
		<%= @event.name %>
		<% if @event.organizer.id == current_user.id %>
		<%= link_to edit_event_path(@event), :method => :get, :title => "Edit event" do %>
              <i class="fa fa-edit"></i>
              <% end %>
        <% end %>
	</h2>

	<p class="event-description"><%= @event.description %></p>

	<table class="table purchase-table">
		<thead>
			<tr>
				<th>Purchases</th>
			</tr>
		</thead>
		<tbody>
			<% @event.purchases.each do |purchase| %>
			<tr>
				<td><%= purchase.description  %></td>
				<td><%= "#{purchase.user.first_name} #{purchase.user.last_name}" %></td>
				<td class="p-amount"><%=number_to_currency(purchase.amount) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<table class="table payment-table">
		<thead>
			<tr>
				<th>Payments</th>
			</tr>
		</thead>
		<tbody>
			<% @event.payments.each do |payment| %>
			<tr>
				<td><%= payment.description%></td>
				<td><%= "#{payment.user.first_name} #{payment.user.last_name}" %></td>
				<td class="p-amount"><%= payment.amount%></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div id="events-right">
	<% if @event.closed %>
		<h2 class="my-h2 closed-text" id="total-text">This event is closed</h2>
	<% end %>
	<h2 class="my-h2" id="total-text">Event total: <text id="total-amount"><%= number_to_currency(@event.total_balance) %></text></h2>
	<h2 class="my-h2" id="total-text">Your split: <text id="total-amount"><%= number_to_currency(@event.total_balance / @event.users.length)%></text></h2>
  <h2 class="my-h2" id="owe-text">You owe: <text id="total-debt"><%= number_to_currency(@event.find_user_event_balance(current_user.id).debt) %></text></h2>
  <h2 class="my-h2" id="owed-text">You're owed: <text id="total-credit"><%= number_to_currency(@event.find_user_event_balance(current_user.id).credit) %></text></h2>

	<% if @event.closed == false %>
		<%= button_to new_purchase_url, :class => 'my-btn gr-btn', :method => :get do %>
		Add Purchase
		<%= hidden_field_tag :event_id, @event.id %>
		<% end %>

		<%= button_to new_payment_url(@event), :class => 'my-btn gr-btn', :method => :get do %>
		Pay up!
		<%= hidden_field_tag :event_id, @event.id %>
		<% end %>

		<% if current_user.id == @event.organizer.id %>
			<%= button_to close_event_path(@event), :method => :get, :title => "Close event", :class => 'my-btn gr-btn', data: {confirm: "Are you sure? This will make users unable to add any more purchases or payments to the event!"} do %>
	        Close event      
	        <% end %>
        <% end %>
	<% end %>

  

   <% if current_user.id == @event.organizer.id %>
	<%= button_to event_path, :method => :delete, :class => 'my-btn gr-btn', :title => "Delete event", data: {confirm: 'Are you sure you want to delete this event?'} do %>
		Delete event
    <% end %>
   <% end %>

</div>  