config/routes.rb
DeborahcGcosmin0LourdProj3::Application.routes.draw do
  resources :users
  resources :sessions
  resources :events
  resources :payments
  resources :purchases

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "landing_page" => "welcome#landing", :as => "landing_page"

  get 'events/:id/close_event' => 'events#close_event', :as => 'close_event'

  root :to => "events#index"

    get '/404' =>'errors#not_found'

  

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :user
	belongs_to :event

	validates :amount, :presence => true

	validate :validate_event_selection
	validate :validate_amount
	validate :validate_event_not_closed

	# Function to make sure a payment is attached to an event
	def validate_event_selection
		unless self.event
			self.errors.add(:event, 'must be chosen.')
		end
	end

	# Function to ensure that user can only pay exactly what they owe to an event
	def validate_amount
		unless self.amount and self.amount > 0 and self.event and self.amount <= self.event.user_event_balances.find_by_user_id(self.user.id).debt
			self.errors.add(:amount, 'You can only pay at most the amount you owe!')

		end
	end

	# Don't add payments if event is closed
	def validate_event_not_closed
		unless self.event and self.event.closed == false
			self.errors.add(:event, 'must not be closed to add payment!')
		end
	end

	def distribute_payment(sender_id, payment)
		@event = self.event
		@user = self.user

		# Convert string to BigDecimal for comparison
		payment = BigDecimal(payment)

		# Distribute payment across all user_event_balances with positive credit (i.e. people who are owed money)
		#self.event.user_event_balances.each do |ueb|
		self.event.user_event_balances.each do |ueb|
			if ueb.user_id == @user.id or ueb.credit <= 0
				next
			end

     		#End when there is no more money to distribute
			if payment <= 0
				break
			end
			# Give each user_event_balance the maximum amount of money from the payment
			ueb.update_payment_received([ueb.credit, payment].min)
			create_new_payment_split_record(@user, ueb.user, payment)
			payment -= [ueb.credit, payment].min
		end
	end

	# Creates a new payment split record that records distribution of payment from sender to a receiver
	def create_new_payment_split_record(sender, receiver, payment )
		sender.payment_splits.create(:user_id => sender, :receiver => receiver, :amount => payment)
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  before_action :check_owner, only: [:edit, :update, :destroy]
  before_action :check_access, only: [:show]

  # GET /payments
  # GET /payments.json
  def index
    @payments = current_user.payments
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new

    @pre_selected_event = get_event_id_from_param(params[:event_id])
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    event_id = payment_params[:event_id]
    @event = Event.find(event_id)

    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        # Distribute payment among users
        @payment.distribute_payment(payment_params[:user_id], payment_params[:amount])
        @payment.event.user_event_balances.each do |ueb|
          ueb.update_debt
          # Distribute payment made by the sender
          ueb.update_credit
        end
        format.html { redirect_to @event, success: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, success: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :description, :event_id, :user_id)
    end

    def check_owner
      unless false # @payment.user_id == current_user.id
        redirect_to :back, :notice => "You can't access this page"
      end
    end

    def check_access
      unless get_users_in_event(@payment.event).include? current_user.id
        redirect_to root_url, :notice => "You can't access this page"
      end
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.number_field :amount, :class => 'text_field', :step => 'any', :placeholder => "Amount" %>
    <%= f.text_area :description, :placeholder => "Description" %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <!--Show list of all events -->
    <%= f.select(:event_id, current_user.events.all.map {|p| [p.name,p.id]}, :prompt => "Select an Event", :selected => @pre_selected_event) %>
    <%= f.submit :class => "my-btn gr-btn"%>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="back-buttons">
  <%= button_to events_path, :class => 'my-btn gr-btn back-btn', :method => :get do %>
    All events
  <% end %>
</div>

<div class="purchases-container">
  <h1>Your payments</h1>
  <table class="table center">
    <thead>
      <tr>
        <th>Event</th>
        <th>Description</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>

    <tbody>
      <% @payments.each do |payment| %>
        <tr>

          <td><%= link_to payment.event.name, event_path(payment.event) %></td>
          <td><%= payment.description %></td>
          <td class="amount"><%= number_to_currency(payment.amount) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/payments/new.html.erb
<div class="back-buttons">
	<%= button_to :back, :class => 'my-btn gr-btn back-btn', :method => :get do %>
		Back
	<% end %>	
</div>

<div class="new-pay-container">

	<h1>New payment</h1>
	<%= render 'form' %>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>