config/routes.rb
DeborahcGcosmin0LourdProj3::Application.routes.draw do
  resources :users
  resources :sessions
  resources :events
  resources :payments
  resources :purchases

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "landing_page" => "welcome#landing", :as => "landing_page"

  get 'events/:id/close_event' => 'events#close_event', :as => 'close_event'

  root :to => "events#index"

    get '/404' =>'errors#not_found'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaymentSplit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
</head>
<body>





<% if current_user %>
<div class="my-navbar">
      <a class="brand pull-left"  <%= link_to "Split-Pay", events_path %></a>
        <p id="logout-text" class="pull-right">
          <strong><%= current_user.email %></strong>
            <%= link_to "Log out", log_out_path %>
            <!--<%= link_to "Sign up", sign_up_path %> -->
            <!-- <%= link_to "log in", log_in_path %> -->
        </p>

</div>
<% end %>

  
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :class => "flash", :id => "flash_#{name}" %>
<% end %>

<!-- <div class="container"> -->
 <%= yield %>
<!-- </div> -->
</body>
</html>